image: tmy2017/gitpod-pstorm-with-php71-mysql8:ver-1663398874
tasks:
  - init: |
      docker-compose pull
      # must use composer v1 newest! already replaced phar file with newest manually and committed
      # and then directly use project provided composer php archive file
      yes | php composer.phar install
      # copy .dist to real config file can just be in init section! 
      cp .env.dist .env
      # database config
      cp config/autoload/local.php.dist config/autoload/local.php
      # to avoid "file not found" error
      chmod 777 .
    command: |
      docker-compose up
  # second terminal to run migration 
  - command: |
      # run migration INSIDE container, must NOT on host machine, see config/autoload/local.php.dist for details
      # wait for db port up then start migration 
      gp await-port 3307 && sleep 7 && yes | docker-compose exec php php bin/migrations.php migrations:migrate
  - command: |
      echo '!!! RUN `docker-compose exec php bin/behat` for e2e testing'
      echo 'sometimes migrations might not work at start of workspace, then run again `docker-compose exec php php bin/migrations.php migrations:migrate`'
ports:
  - port: 8080
    visibility: private
    onOpen: open-preview
  # actually use 3307, this port is legacy from workspace-mysql, thus ignore to reduce confusion
  - port: 3306
    onOpen: ignore
