tasks:
  - init: |
      docker-compose pull
      # must use composer v1, hence directly use project provided composer php archive file
      yes | php composer.phar install
    command: |
      cp .env.dist .env
      # to avoid "file not found" error
      chmod 777 .
      docker-compose up
ports:
  - port: 8080
    visibility: private
    onOpen: open-preview