image: tmy2017/gitpod-pstorm-with-php71-mysql8:ver-1645387802
tasks:
  - init: |
      docker-compose pull
      # must use composer v1 newest! already replaced phar file with newest manually and committed
      # and then directly use project provided composer php archive file
      yes | php composer.phar install
    command: |
      cp .env.dist .env
      # to avoid "file not found" error
      chmod 777 .
      docker-compose up
ports:
  - port: 8080
    visibility: private
    onOpen: open-preview