version: '2'
services:
  nginx:
    image: prooph/nginx:www
    ports:
        - "${NGINX_PORT}:80"
        - "443:443"
    links:
      - php:php
    volumes:
      - .:/var/www

  php:
    image: prooph/php:7.1-fpm-xdebug
    extra_hosts : [ host.docker.internal:host-gateway]
    links:
      - mariadb:mariadb
    volumes:
      - .:/var/www
      # now use custom tmy image - https://github.dev/tmy2017/php-ddd-example/blob/2b7ae4f92c5619810efbe3252ca6171713c45cb2/.gitpod.gitpod-pstorm-with-php71-mysql8.Dockerfile#L50
      - /usr/local/etc/xdebug2.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # if not then download xdebug.ini and put in project root
      # - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  mariadb:
    image: mariadb
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=cargo_sample

  adminer:
    image: adminer:4.3
    ports:
      - ${ADMINER_PORT}:8080